# fly.toml app configuration file generated for teste-backend-amicci on 2024-04-28T02:04:28-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'teste-backend-amicci'
primary_region = 'gru'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'bash release.sh'

[env]
  PORT = '8000'
  ENV = 'production'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/staticfiles'
  url_prefix = '/static/'
